# ./docker-compose.yml

version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      -
      -
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - "5601:5601"

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    restart: unless-stopped
    volumes:
      -
      -
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
    expose:
      - 9090
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    links:
      - prometheus:prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      #- GF_SECURITY_ADMIN_PASSWORD=MYPASSWORT
      #- GF_USERS_ALLOW_SIGN_UP=false
      #- GF_SERVER_DOMAIN=myrul.com
      #- GF_SMTP_ENABLED=true
      #- GF_SMTP_HOST=smtp.gmail.com:587
      #- GF_SMTP_USER=myadrress@gmail.com
      #- GF_SMTP_PASSWORD=mypassword
      #- GF_SMTP_FROM_ADDRESS=myaddress@gmail.com

  kafka:

    volumes:
      - /path/to/kafka-persistence:/bitnami/kafka

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"