# ./docker-compose.yml

version: '3'

services:
  auth:
    image: microservice_auth
    ports:
      - "8000:8000"

  market:
    image: microservice_market
    ports:
      - "8001:8001"

  membership:
    image: microservice_membership
    ports:
      - "8002:8002"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus:v2.11.1
    container_name: prometheus
    ports:
    - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
    - "80:3000"
    depends_on:
      - prometheus

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    ports:
      - "12181:12181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-1
    ports:
      - "19092:19092"
    depends_on:
      - zookeeper

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: elasticsearch
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    container_name: kibana
    ports:
    - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://localhost:9200
      ELASTICSEARCH_HOSTS: '["http://localhost:9200"]'
    depends_on:
      - elasticsearch
